# Configuration of Mementos runtime library would go here
# (see mementos/Makefile.config for available options).

# Ugly, but needed since otherwise libraries are attempted to built with mementos
override TOOLCHAIN = clang

include ../Makefile
include $(MEMENTOS_ROOT)/Makefile.target
