EXEC = blinker

OBJECTS = \
	main.o \

DEPS += \
	libmsp \

# This makefile is meant to be invoked indirectly by a makefile in
# per-toolchain build-dir, hence the rel path is from that dir.
SRC_ROOT = ../../src
